#### SEML and SLURM config

seml:
  executable: main.py
  name: CIFAR10_LeNet5_global_noise_layer_repetition
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter


#### Experiment config

fixed:
  general:
    num_epochs: 300
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: CIFAR10
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None
  noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
      enable_in_training: False

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 100
    step: 1


no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise
  grid:
    model.LeNet.conf_name:
      type: choice
      options:
        - LeNet5-BN
        - LeNet5


global_repetition_BN:
  fixed:
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.conf_name:
      type: choice
      options:
        - LeNet5-BN
    model.LeNet.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20

global_repetition_noBN:
  fixed:
    noise_settings.default.GaussStd: 0.250
  grid:
    model.LeNet.conf_name:
      type: choice
      options:
        - LeNet5
    model.LeNet.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20



layer_repetition_with_BN_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_log10_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,2,3,3,3,1,3,4,1,1,1,2,1,1,1,1,]
        - [5,3,5,5,5,1,5,7,2,1,2,3,1,1,1,1,]
        - [10,6,8,9,8,1,8,12,4,1,3,6,1,1,1,1,]
        - [14,8,12,13,12,2,12,16,5,1,5,8,1,1,1,1,]
        - [20,12,17,18,17,3,17,24,8,1,7,12,1,1,1,1,]
        - [40,24,34,38,35,6,34,48,16,1,14,24,1,1,3,1,]

layer_repetition_with_BN_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_sqrt_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,2,2,2,2,2,3,2,1,2,2,2,2,2,1,]
        - [4,3,4,4,4,3,4,4,3,1,3,3,2,2,3,1,]
        - [6,6,6,6,6,5,6,6,5,2,5,6,4,4,5,2,]
        - [9,8,8,9,9,7,9,9,7,3,7,8,5,5,6,3,]
        - [13,11,12,12,12,10,12,13,11,4,10,11,8,8,9,4,]
        - [25,23,24,25,25,19,24,26,21,8,21,23,15,15,18,8,]

layer_repetition_with_BN_inverse_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,2,3,3,2,2,3,2,1,2,2,1,1,2,1,]
        - [4,3,4,4,4,3,4,5,3,1,3,3,2,2,2,1,]
        - [7,5,6,7,7,4,6,8,5,2,5,6,3,3,4,2,]
        - [10,7,9,9,9,6,9,11,7,3,6,8,5,5,5,3,]
        - [14,11,13,13,13,8,13,16,9,5,9,11,6,6,8,5,]
        - [28,21,25,27,26,16,26,32,19,9,18,22,13,13,16,9,]

layer_repetition_with_BN_inverse_lin_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,3,3,3,1,3,4,2,1,1,2,1,1,1,1,]
        - [5,3,4,5,4,2,4,7,3,1,2,3,1,1,2,1,]
        - [9,5,7,8,8,3,7,11,4,1,4,5,2,2,3,1,]
        - [12,7,10,11,10,4,10,16,6,1,6,7,3,3,4,2,]
        - [18,10,14,16,15,6,15,23,8,2,8,10,4,4,5,2,]
        - [35,21,29,32,30,12,29,45,16,4,15,21,8,8,11,4,]

layer_repetition_with_BN_inverse_square_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,1,3,3,3,1,3,6,1,1,1,1,1,1,1,1,]
        - [6,2,4,5,5,1,5,11,1,1,1,2,1,1,1,1,]
        - [11,4,7,9,8,1,8,18,3,1,2,4,1,1,1,1,]
        - [16,5,10,13,11,2,11,26,3,1,3,6,1,1,2,1,]
        - [23,8,15,19,16,3,16,37,5,1,4,8,1,1,2,1,]
        - [45,16,30,39,32,5,32,75,10,1,9,16,2,2,5,1,]

layer_repetition_with_BN_inverse_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [1,1,1,1,1,2,1,1,10,1,6,1,1,1,2,1,]
        - [1,1,1,1,1,3,1,1,18,1,10,1,2,2,3,1,]
        - [1,1,1,1,1,6,1,1,33,2,18,1,3,3,5,2,]
        - [1,1,1,1,1,9,1,1,48,2,27,1,4,4,7,3,]
        - [1,1,1,1,1,13,1,1,71,3,39,1,6,6,11,3,]
        - [1,1,1,1,1,27,1,1,145,7,80,1,12,12,22,7,]

layer_repetition_with_BN_layer_sort_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [2,4,3,3,2,3,1,3,2,1,2,1,1,1,1,2,]
        - [3,6,5,4,3,5,2,5,3,2,4,1,1,1,1,2,]
        - [5,9,8,7,6,8,3,9,5,4,6,1,2,2,1,4,]
        - [7,13,11,10,8,12,4,12,7,5,9,2,2,3,1,6,]
        - [11,19,15,14,12,16,6,18,9,7,13,2,4,5,1,8,]
        - [21,38,31,28,24,33,12,35,19,14,26,5,7,9,2,16,]

layer_repetition_with_BN_layer_sort_inverse_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [1,9,2,2,1,3,1,4,1,1,2,1,1,1,1,1,]
        - [2,14,4,3,2,5,1,7,2,1,2,1,1,1,1,1,]
        - [3,24,6,5,3,8,2,12,3,2,4,1,2,2,1,2,]
        - [4,33,8,7,5,11,3,17,4,3,5,2,2,3,2,3,]
        - [6,47,12,9,7,16,4,24,5,4,8,3,3,4,3,5,]
        - [12,95,24,19,13,32,8,47,10,9,16,6,7,7,6,9,]

layer_repetition_with_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [2,3,3,3,2,3,1,3,2,1,3,1,1,1,1,2,]
        - [3,5,5,4,3,5,2,5,3,2,4,1,1,1,1,3,]
        - [6,9,8,7,6,8,3,9,4,3,7,1,2,2,1,4,]
        - [8,12,11,9,8,11,5,12,6,5,9,2,3,3,2,6,]
        - [11,18,16,13,11,16,7,18,9,7,13,2,4,4,2,9,]
        - [22,36,31,27,22,31,13,36,18,13,27,4,9,9,4,18,]

layer_repetition_with_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [2,3,3,3,2,3,1,3,2,2,3,1,1,1,1,1,]
        - [3,5,4,4,3,5,2,5,3,2,4,1,2,2,1,2,]
        - [5,8,6,7,5,8,4,8,5,4,6,3,3,3,1,4,]
        - [7,11,9,9,7,11,5,11,7,6,9,4,4,4,2,6,]
        - [11,16,13,13,10,16,8,16,10,8,13,5,5,5,3,8,]
        - [21,31,26,26,21,31,16,31,21,16,26,11,11,11,5,16,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [1,6,3,2,1,3,1,6,1,1,2,1,1,1,1,1,]
        - [2,9,4,3,2,4,2,9,2,2,3,1,1,1,1,2,]
        - [4,15,7,5,4,7,2,15,3,2,5,2,2,2,2,3,]
        - [5,21,10,7,5,10,3,21,4,3,7,3,3,3,3,4,]
        - [7,29,15,10,7,15,5,29,6,5,10,4,4,4,4,6,]
        - [15,59,29,20,15,29,10,59,12,10,20,7,8,8,7,12,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.197
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [2,4,2,2,2,4,1,5,2,1,2,1,1,1,1,1,]
        - [2,7,4,4,2,7,2,7,2,2,3,1,1,1,1,2,]
        - [4,11,6,6,4,11,3,11,4,3,6,2,2,2,2,3,]
        - [6,16,8,8,5,16,4,16,5,4,8,3,3,3,3,4,]
        - [8,23,11,11,8,23,6,23,8,6,11,4,4,4,4,6,]
        - [15,46,23,23,15,46,11,46,15,11,23,9,9,9,8,11,]







layer_repetition_no_BN_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_log10_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,4,3,2,3,1,1,1,1,1,1,]
        - [6,5,6,5,2,5,2,1,1,1,1,1,]
        - [10,9,10,9,5,8,4,1,1,1,1,1,]
        - [14,13,15,12,7,12,6,1,1,1,1,1,]
        - [21,19,21,18,10,18,8,1,1,1,1,1,]
        - [43,38,44,37,20,36,17,1,1,1,1,1,]

layer_repetition_no_BN_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_sqrt_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,3,2,3,2,1,1,1,1,1,]
        - [4,4,4,4,4,4,3,2,2,1,2,2,]
        - [7,7,7,7,6,7,5,2,4,2,3,3,]
        - [10,10,10,9,8,9,8,3,5,2,5,5,]
        - [14,14,14,13,12,13,11,5,7,3,7,7,]
        - [28,27,28,27,23,27,22,10,14,7,13,14,]

layer_repetition_no_BN_inverse_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,3,2,3,2,1,1,1,1,1,]
        - [5,4,5,4,3,4,3,1,2,1,2,2,]
        - [8,7,9,7,5,7,4,2,3,2,3,3,]
        - [11,10,12,10,7,10,6,3,4,3,4,4,]
        - [17,15,17,14,10,14,9,5,5,4,5,5,]
        - [33,30,34,29,19,28,18,9,11,8,10,11,]

layer_repetition_no_BN_inverse_lin_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,3,4,3,1,3,1,1,1,1,1,1,]
        - [6,5,7,5,2,4,2,1,1,1,1,1,]
        - [11,9,12,8,4,8,3,1,1,1,1,1,]
        - [16,12,16,12,5,11,4,1,2,1,2,2,]
        - [22,18,23,17,8,16,6,2,3,1,2,2,]
        - [45,36,46,33,15,32,13,3,5,3,4,5,]

layer_repetition_no_BN_inverse_square_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,3,5,3,1,2,1,1,1,1,1,1,]
        - [8,5,8,4,1,4,1,1,1,1,1,1,]
        - [14,9,15,8,1,7,1,1,1,1,1,1,]
        - [20,13,21,11,2,10,2,1,1,1,1,1,]
        - [29,18,31,16,3,15,3,1,1,1,1,1,]
        - [59,37,64,33,7,30,5,1,1,1,1,1,]

layer_repetition_no_BN_inverse_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,4,2,4,1,4,1,1,1,1,1,1,]
        - [4,6,4,7,1,8,1,1,1,1,1,1,]
        - [8,11,7,13,1,14,1,1,1,1,1,1,]
        - [12,16,11,18,1,20,1,1,1,1,1,1,]
        - [17,24,16,26,1,30,1,1,1,1,1,1,]
        - [34,49,33,55,1,62,1,1,1,1,1,1,]

layer_repetition_no_BN_layer_sort_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,4,3,3,2,2,2,1,1,1,1,1,]
        - [5,5,5,4,3,4,3,2,1,1,2,1,]
        - [8,9,8,7,5,6,5,3,1,2,4,2,]
        - [11,13,12,10,8,9,6,4,1,2,5,3,]
        - [15,18,17,14,11,12,9,6,2,3,8,5,]
        - [31,37,34,28,22,25,18,12,3,6,15,9,]

layer_repetition_no_BN_layer_sort_inverse_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [2,7,4,2,1,2,1,1,1,1,1,1,]
        - [4,12,6,3,2,2,2,1,1,1,1,1,]
        - [6,19,10,5,3,4,3,2,2,2,2,2,]
        - [9,27,14,7,5,5,4,3,2,2,3,3,]
        - [13,39,19,10,6,8,6,4,3,3,5,4,]
        - [26,77,39,19,13,15,11,9,6,7,10,8,]

layer_repetition_no_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,3,2,2,2,1,1,1,2,1,]
        - [4,5,5,4,3,3,3,2,1,1,3,2,]
        - [7,9,9,7,6,6,4,3,1,1,4,3,]
        - [10,12,12,10,8,8,6,4,2,2,6,4,]
        - [14,17,17,14,11,11,9,6,3,3,9,6,]
        - [29,34,34,29,23,23,17,11,6,6,17,11,]

layer_repetition_no_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,2,2,2,2,2,1,1,2,1,]
        - [5,5,5,4,4,4,2,2,1,1,2,1,]
        - [8,8,8,6,6,6,4,4,2,2,4,2,]
        - [11,11,11,8,8,8,6,6,3,3,6,3,]
        - [16,16,16,12,12,12,8,8,4,4,8,4,]
        - [32,32,32,24,24,24,16,16,8,8,16,8,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [2,5,5,2,2,2,1,1,1,1,1,1,]
        - [4,7,7,4,2,2,2,2,1,1,2,2,]
        - [6,12,12,6,4,4,3,3,2,2,3,3,]
        - [9,17,17,9,6,6,4,3,3,3,4,3,]
        - [12,25,25,12,8,8,6,5,4,4,6,5,]
        - [25,49,49,25,16,16,12,10,8,8,12,10,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.25
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,4,4,2,2,2,1,1,1,1,1,1,]
        - [6,6,6,3,3,3,2,2,1,1,2,1,]
        - [10,10,10,5,5,5,3,3,2,2,3,2,]
        - [13,13,13,7,7,7,5,5,3,3,5,3,]
        - [19,19,19,10,10,10,6,6,5,5,6,5,]
        - [38,38,38,19,19,19,13,13,10,10,13,10,]

