#### SEML and SLURM config

seml:
  executable: main.py
  name: MNIST_LeNet5_global_noise_layer_repetition
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter


#### Experiment config

fixed:
  general:
    num_epochs: 50
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: MNIST
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None
  noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
      enable_in_training: False

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 400
    step: 1


no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise
  grid:
    model.LeNet.conf_name:
      type: choice
      options:
        - LeNet5-BN
        - LeNet5


global_repetition_BN:
  fixed:
    noise_settings.default.GaussStd: 0.238
  grid:
    model.LeNet.conf_name:
      type: choice
      options:
        - LeNet5-BN
    model.LeNet.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20

global_repetition_noBN:
  fixed:
    noise_settings.default.GaussStd: 0.607
  grid:
    model.LeNet.conf_name:
      type: choice
      options:
        - LeNet5
    model.LeNet.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20


layer_repetition_with_BN_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_log10_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,4,2,3,2,2,2,3,2,1,1,2,1,1,1,1,]
        - [6,6,4,4,4,3,4,4,3,1,2,3,1,1,1,1,]
        - [10,11,6,7,6,5,6,7,5,2,4,6,2,1,1,1,]
        - [14,15,8,10,9,7,9,10,8,3,5,8,3,1,1,1,]
        - [20,22,12,14,12,10,12,15,11,4,8,11,5,1,2,1,]
        - [41,44,24,29,24,21,25,30,21,9,15,23,9,1,3,1,]

layer_repetition_with_BN_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_sqrt_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,2,2,2,2,2,2,2,2,2,2,2,1,2,1,]
        - [4,4,3,4,3,3,3,4,3,3,3,3,3,2,2,1,]
        - [6,7,6,6,6,5,6,6,5,4,5,6,4,3,4,1,]
        - [9,9,8,8,8,8,8,8,8,6,7,8,6,4,5,2,]
        - [13,13,11,12,11,11,11,12,11,9,10,11,9,7,7,2,]
        - [26,26,22,24,23,22,23,24,22,17,20,22,17,13,15,4,]

layer_repetition_with_BN_inverse_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,4,2,2,2,2,2,3,2,1,2,2,1,1,1,1,]
        - [5,6,3,4,3,3,3,4,3,2,2,3,2,2,2,1,]
        - [9,10,5,6,5,5,6,6,5,3,4,5,3,3,3,2,]
        - [13,14,7,9,7,7,7,9,7,5,6,7,5,3,4,2,]
        - [18,20,11,12,11,10,11,13,10,6,8,10,7,5,5,3,]
        - [36,40,21,25,21,19,22,26,20,13,16,20,13,10,11,7,]

layer_repetition_with_BN_inverse_lin_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,6,2,2,2,1,2,3,1,1,1,2,1,1,1,1,]
        - [8,10,3,4,3,2,3,4,2,1,2,2,1,1,1,1,]
        - [14,16,5,6,5,4,5,7,4,2,3,4,2,1,1,1,]
        - [19,23,7,9,7,5,7,10,6,2,4,6,3,1,2,1,]
        - [28,33,9,13,10,8,10,14,8,4,5,9,4,2,2,1,]
        - [55,66,19,26,20,16,20,28,16,7,11,18,7,4,5,2,]

layer_repetition_with_BN_inverse_square_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [7,10,1,1,1,1,1,2,1,1,1,1,1,1,1,1,]
        - [12,17,1,3,1,1,2,3,1,1,1,1,1,1,1,1,]
        - [21,30,2,5,2,2,3,5,2,1,1,2,1,1,1,1,]
        - [30,43,3,7,4,2,4,7,3,1,1,3,1,1,1,1,]
        - [43,62,5,10,5,3,6,11,4,1,2,4,1,1,1,1,]
        - [88,125,10,19,11,7,11,22,8,1,4,9,2,1,1,1,]

layer_repetition_with_BN_inverse_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [1,1,2,5,2,1,2,10,1,1,1,1,1,1,1,1,]
        - [1,1,3,9,3,2,3,16,2,1,1,2,1,1,1,1,]
        - [1,1,5,16,5,3,5,29,3,1,2,4,2,1,1,1,]
        - [1,1,6,23,7,4,7,41,5,2,3,6,2,1,2,1,]
        - [1,1,9,33,10,6,10,59,7,3,4,8,3,2,2,2,]
        - [1,1,18,65,20,13,21,118,14,6,9,16,6,4,5,3,]

layer_repetition_with_BN_layer_sort_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,4,2,3,2,3,3,1,2,2,1,1,2,1,1,1,]
        - [5,6,3,5,3,4,5,2,3,4,2,1,2,1,1,1,]
        - [9,9,5,8,6,7,8,3,5,6,4,2,4,1,2,1,]
        - [12,13,7,11,8,10,12,4,7,9,5,3,6,2,2,1,]
        - [18,19,11,15,12,14,16,6,9,13,7,5,8,2,4,1,]
        - [35,38,21,31,24,28,33,12,19,26,14,9,16,5,7,2,]

layer_repetition_with_BN_layer_sort_inverse_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,9,1,2,1,2,3,1,1,2,1,1,1,1,1,1,]
        - [7,14,2,4,2,3,5,1,2,2,1,1,1,1,1,1,]
        - [12,24,3,6,3,5,8,2,3,4,2,2,2,1,2,1,]
        - [17,33,4,8,5,7,11,3,4,5,3,3,3,2,2,2,]
        - [24,47,6,12,7,9,16,4,5,8,4,4,5,3,3,3,]
        - [47,95,12,24,13,19,32,8,10,16,9,7,9,6,7,6,]

layer_repetition_with_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,2,3,2,3,3,1,2,3,1,1,2,1,1,1,]
        - [5,5,3,5,3,4,5,2,3,4,2,1,3,1,1,1,]
        - [9,9,6,8,6,7,8,3,4,7,3,2,4,1,2,1,]
        - [12,12,8,11,8,9,11,5,6,9,5,3,6,2,3,2,]
        - [18,18,11,16,11,13,16,7,9,13,7,4,9,2,4,2,]
        - [36,36,22,31,22,27,31,13,18,27,13,9,18,4,9,4,]

layer_repetition_with_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,2,3,2,3,3,1,2,3,2,1,1,1,1,1,]
        - [5,5,3,4,3,4,5,2,3,4,2,2,2,2,1,1,]
        - [8,8,5,7,5,6,8,4,5,6,4,3,4,3,3,1,]
        - [11,11,7,9,7,9,11,5,7,9,6,4,6,4,4,2,]
        - [16,16,10,13,11,13,16,8,10,13,8,5,8,5,5,3,]
        - [31,31,21,26,21,26,31,16,21,26,16,11,16,11,11,5,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [6,6,1,3,1,2,3,1,1,2,1,1,1,1,1,1,]
        - [9,9,2,4,2,3,4,2,2,3,2,1,2,1,1,1,]
        - [15,15,4,7,4,5,7,2,3,5,2,2,3,2,2,2,]
        - [21,21,5,10,5,7,10,3,4,7,3,3,4,3,3,3,]
        - [29,29,7,15,7,10,15,5,6,10,5,4,6,4,4,4,]
        - [59,59,15,29,15,20,29,10,12,20,10,8,12,7,8,7,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.238
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,4,2,2,2,2,4,1,2,2,1,1,1,1,1,1,]
        - [7,7,2,4,2,3,7,2,2,4,2,1,2,1,1,1,]
        - [11,11,4,6,4,6,11,3,4,6,3,2,3,2,2,2,]
        - [16,16,6,8,5,8,16,4,5,8,4,3,4,3,3,3,]
        - [23,23,8,11,8,11,23,6,8,11,6,4,6,4,4,4,]
        - [46,46,15,23,15,23,46,11,15,23,11,9,11,9,9,8,]




layer_repetition_no_BN_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_log10_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,3,3,3,2,2,2,1,1,1,1,1,]
        - [6,5,5,4,3,4,3,1,2,1,1,1,]
        - [10,8,8,8,6,7,5,2,3,1,1,1,]
        - [15,11,12,11,8,10,7,3,4,1,1,1,]
        - [21,16,17,16,12,14,10,4,6,1,2,1,]
        - [42,33,35,32,24,27,21,7,12,2,4,1,]

layer_repetition_no_BN_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_sqrt_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,3,2,2,2,1,2,1,1,1,]
        - [4,4,4,4,4,4,3,2,3,1,2,1,]
        - [8,7,7,7,6,6,6,3,4,2,3,1,]
        - [10,10,10,9,8,9,8,5,6,3,4,2,]
        - [15,14,14,13,12,13,11,7,9,4,5,3,]
        - [30,27,28,27,24,26,23,14,17,8,11,5,]

layer_repetition_no_BN_inverse_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,3,3,3,2,2,2,1,1,1,1,1,]
        - [6,4,5,4,3,4,3,2,2,1,1,1,]
        - [10,7,8,7,5,6,5,3,3,2,2,2,]
        - [15,10,11,10,7,8,6,4,4,3,3,3,]
        - [21,14,16,14,10,12,9,5,6,4,5,4,]
        - [42,29,31,28,21,23,18,10,13,8,9,8,]

layer_repetition_no_BN_inverse_lin_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [6,3,3,3,1,2,1,1,1,1,1,1,]
        - [10,5,5,4,2,3,2,1,1,1,1,1,]
        - [17,8,9,8,4,5,3,1,2,1,1,1,]
        - [24,12,13,11,6,7,4,2,2,1,1,1,]
        - [34,17,19,16,8,11,6,2,3,1,2,1,]
        - [69,33,38,32,16,21,13,4,6,3,3,2,]

layer_repetition_no_BN_inverse_square_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,2,3,2,1,1,1,1,1,1,1,1,]
        - [16,4,5,3,1,1,1,1,1,1,1,1,]
        - [28,6,9,6,2,3,1,1,1,1,1,1,]
        - [41,9,13,9,2,4,1,1,1,1,1,1,]
        - [59,14,18,13,3,6,2,1,1,1,1,1,]
        - [121,28,37,26,7,12,4,1,1,1,1,1,]

layer_repetition_no_BN_inverse_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [13,1,1,1,1,1,1,1,1,1,1,1,]
        - [25,1,1,1,1,1,1,1,1,1,1,1,]
        - [49,1,1,1,1,1,1,1,1,1,1,1,]
        - [73,1,1,1,1,1,1,1,1,1,1,1,]
        - [109,1,1,1,1,1,1,1,1,1,1,1,]
        - [229,1,1,1,1,1,1,1,1,1,1,1,]

layer_repetition_no_BN_layer_sort_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,3,3,3,2,2,2,1,1,1,1,1,]
        - [5,5,5,4,3,4,3,2,2,1,1,1,]
        - [9,8,8,7,5,6,5,3,4,2,2,1,]
        - [13,11,12,10,8,9,6,4,5,2,3,1,]
        - [18,15,17,14,11,12,9,6,8,3,5,2,]
        - [37,31,34,28,22,25,18,12,15,6,9,3,]

layer_repetition_no_BN_layer_sort_inverse_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [7,2,4,2,1,2,1,1,1,1,1,1,]
        - [12,4,6,3,2,2,2,1,1,1,1,1,]
        - [19,6,10,5,3,4,3,2,2,2,2,2,]
        - [27,9,14,7,5,5,4,3,3,2,3,2,]
        - [39,13,19,10,6,8,6,4,5,3,4,3,]
        - [77,26,39,19,13,15,11,9,10,7,8,6,]

layer_repetition_no_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,3,2,2,2,1,2,1,1,1,]
        - [5,4,5,4,3,3,3,2,3,1,2,1,]
        - [9,7,9,7,6,6,4,3,4,1,3,1,]
        - [12,10,12,10,8,8,6,4,6,2,4,2,]
        - [17,14,17,14,11,11,9,6,9,3,6,3,]
        - [34,29,34,29,23,23,17,11,17,6,11,6,]

layer_repetition_no_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,2,2,2,2,2,2,1,1,1,]
        - [5,5,5,4,4,4,2,2,2,1,1,1,]
        - [8,8,8,6,6,6,4,4,4,2,2,2,]
        - [11,11,11,8,8,8,6,6,6,3,3,3,]
        - [16,16,16,12,12,12,8,8,8,4,4,4,]
        - [32,32,32,24,24,24,16,16,16,8,8,8,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,2,5,2,2,2,1,1,1,1,1,1,]
        - [7,4,7,4,2,2,2,2,2,1,2,1,]
        - [12,6,12,6,4,4,3,3,3,2,3,2,]
        - [17,9,17,9,6,6,4,3,4,3,3,3,]
        - [25,12,25,12,8,8,6,5,6,4,5,4,]
        - [49,25,49,25,16,16,12,10,12,8,10,8,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.607
    noise_settings.default.enable_in_training: False
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,4,4,2,2,2,1,1,1,1,1,1,]
        - [6,6,6,3,3,3,2,2,2,1,1,1,]
        - [10,10,10,5,5,5,3,3,3,2,2,2,]
        - [13,13,13,7,7,7,5,5,5,3,3,3,]
        - [19,19,19,10,10,10,6,6,6,5,5,5,]
        - [38,38,38,19,19,19,13,13,13,10,10,10,]









