#### SEML and SLURM config

seml:
  executable: main.py
  name: MNIST_mlp_TFC_global_noise_layer_repetition
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter


#### Experiment config

fixed:
  general:
    num_epochs: 100
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: MNIST
  model:
    model_class: MLP
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None
  noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
      enable_in_training: False

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 100
    step: 1


no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise
  grid:
    model.MLP.conf_name:
      type: choice
      options:
        - RL_TFC
        - RL_TFC-noBN

global_repetition_BN:
  fixed:
    noise_settings.default.GaussStd: 0.350
  grid:
    model.MLP.conf_name:
      type: choice
      options:
        - RL_TFC
    model.MLP.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20

global_repetition_noBN:
  fixed:
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.conf_name:
      type: choice
      options:
        - RL_TFC-noBN
    model.MLP.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20



layer_repetition_with_BN_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_log10_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,2,3,3,2,2,2,1,1,1,1,]
        - [5,3,4,5,4,3,4,2,1,1,1,]
        - [10,5,7,8,6,5,6,4,1,2,1,]
        - [13,7,10,11,9,7,9,5,2,3,1,]
        - [19,10,14,16,13,10,13,8,2,4,1,]
        - [39,20,28,32,26,21,26,15,5,7,1,]

layer_repetition_with_BN_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_sqrt_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,2,2,2,2,2,2,2,2,1,]
        - [4,3,4,4,3,3,4,3,2,2,1,]
        - [7,5,6,6,6,5,6,5,4,4,1,]
        - [9,8,8,9,8,8,8,7,5,6,1,]
        - [13,11,12,12,12,11,12,10,7,8,2,]
        - [26,22,24,25,23,22,23,20,15,16,4,]

layer_repetition_with_BN_inverse_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,2,2,3,2,2,2,2,1,1,1,]
        - [6,3,4,4,3,3,3,2,2,2,1,]
        - [9,5,6,7,6,5,6,4,3,3,1,]
        - [13,7,9,10,8,7,8,5,4,4,2,]
        - [19,9,13,15,11,9,12,8,5,6,3,]
        - [38,19,25,29,23,19,23,15,11,12,6,]

layer_repetition_with_BN_inverse_lin_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [6,1,3,3,2,1,2,1,1,1,1,]
        - [9,2,4,5,3,2,3,2,1,1,1,]
        - [15,4,7,9,5,4,6,2,1,1,1,]
        - [21,5,9,13,8,5,8,3,2,2,1,]
        - [30,8,13,18,11,8,11,5,2,3,1,]
        - [59,15,27,36,22,15,23,10,5,6,2,]

layer_repetition_with_BN_inverse_square_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,1,2,3,1,1,1,1,1,1,1,]
        - [15,1,3,5,2,1,2,1,1,1,1,]
        - [26,2,5,9,3,2,4,1,1,1,1,]
        - [37,2,8,14,5,2,5,1,1,1,1,]
        - [53,3,11,20,7,3,8,2,1,1,1,]
        - [107,7,22,40,15,7,16,3,1,1,1,]

layer_repetition_with_BN_inverse_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [1,1,7,1,3,2,3,1,1,1,1,]
        - [1,2,12,1,5,2,5,2,1,1,1,]
        - [1,4,21,1,9,4,9,2,1,2,1,]
        - [1,5,30,1,12,6,13,4,2,2,1,]
        - [1,8,43,1,17,8,19,5,3,3,2,]
        - [1,15,87,1,35,16,38,10,6,7,4,]

layer_repetition_with_BN_layer_sort_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,2,2,2,3,1,1,1,1,]
        - [5,4,4,3,3,3,5,2,1,2,1,]
        - [9,7,7,4,6,5,8,3,2,3,1,]
        - [13,9,10,6,8,7,12,5,2,4,1,]
        - [18,13,15,8,12,10,17,7,3,5,2,]
        - [37,27,30,17,23,20,33,13,7,10,3,]

layer_repetition_with_BN_layer_sort_inverse_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [7,2,2,1,1,1,4,1,1,1,1,]
        - [11,3,4,2,2,2,5,1,1,1,1,]
        - [18,4,6,3,4,3,9,2,2,2,2,]
        - [25,6,9,4,5,4,13,3,3,3,2,]
        - [37,9,12,5,7,6,18,5,4,4,3,]
        - [73,18,24,10,15,12,37,9,7,8,7,]

layer_repetition_with_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,2,2,2,3,1,1,1,1,]
        - [5,4,4,2,3,3,5,2,2,2,1,]
        - [8,7,7,4,5,5,8,4,3,3,1,]
        - [11,9,9,6,7,8,11,6,4,4,2,]
        - [16,13,14,8,11,11,16,8,5,5,3,]
        - [32,27,27,16,22,21,32,16,11,11,5,]

layer_repetition_with_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,3,2,2,2,3,2,1,1,1,]
        - [5,4,5,2,3,3,5,2,1,2,1,]
        - [7,6,7,4,6,6,7,4,2,4,2,]
        - [11,8,11,5,8,8,10,5,3,5,3,]
        - [15,11,15,8,11,11,15,8,4,8,4,]
        - [30,23,30,15,23,23,30,15,8,15,8,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,2,2,1,1,2,5,1,1,1,1,]
        - [7,4,4,2,2,2,7,2,1,1,1,]
        - [12,6,6,3,4,4,11,3,2,2,2,]
        - [16,8,8,4,6,6,16,4,3,3,3,]
        - [23,11,11,6,8,8,23,6,5,5,4,]
        - [46,23,23,12,16,16,46,12,9,9,8,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.35
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,2,4,1,2,2,3,1,1,1,1,]
        - [6,3,5,2,3,3,5,2,1,2,1,]
        - [9,5,9,3,5,5,9,3,2,3,2,]
        - [13,7,13,4,6,7,13,4,3,4,3,]
        - [18,9,18,6,9,9,19,6,5,6,5,]
        - [37,19,37,12,18,18,37,12,9,12,9,]






layer_repetition_no_BN_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_log10_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,2,3,1,2,1,1,1,]
        - [8,4,4,2,3,1,1,1,]
        - [14,7,8,4,4,1,1,1,]
        - [20,10,11,5,7,1,1,1,]
        - [29,14,17,8,9,1,1,1,]
        - [59,29,34,16,19,1,1,1,]

layer_repetition_no_BN_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_sqrt_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,2,2,1,1,1,]
        - [5,4,4,3,3,2,2,1,]
        - [8,7,7,5,6,3,3,1,]
        - [11,9,9,8,8,5,5,1,]
        - [16,13,14,11,11,6,7,2,]
        - [31,26,27,22,23,13,14,4,]

layer_repetition_no_BN_inverse_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,2,3,1,2,1,1,1,]
        - [8,3,4,2,3,1,2,1,]
        - [14,6,6,4,4,2,2,2,]
        - [20,8,9,5,6,3,3,2,]
        - [28,11,13,7,8,5,5,3,]
        - [55,22,26,15,17,9,10,6,]

layer_repetition_no_BN_inverse_lin_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [8,1,2,1,1,1,1,1,]
        - [14,2,3,1,1,1,1,1,]
        - [24,4,5,2,2,1,1,1,]
        - [34,6,7,3,3,1,1,1,]
        - [49,8,11,4,4,1,2,1,]
        - [99,16,22,7,9,3,3,1,]

layer_repetition_no_BN_inverse_square_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,1,1,1,1,1,1,1,]
        - [17,1,1,1,1,1,1,1,]
        - [32,1,2,1,1,1,1,1,]
        - [48,1,2,1,1,1,1,1,]
        - [70,2,3,1,1,1,1,1,]
        - [144,4,7,1,1,1,1,1,]

layer_repetition_no_BN_inverse_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [1,3,5,2,2,1,1,1,]
        - [1,5,7,3,3,2,2,1,]
        - [1,8,11,5,6,3,3,3,]
        - [1,11,16,7,8,4,5,4,]
        - [1,17,22,10,11,7,7,5,]
        - [1,34,45,20,22,13,14,11,]

layer_repetition_no_BN_layer_sort_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,2,2,1,1,1,]
        - [5,4,5,3,3,1,2,1,]
        - [9,7,8,4,6,2,3,1,]
        - [12,9,11,6,8,3,5,2,]
        - [18,13,16,9,11,4,7,2,]
        - [36,27,31,18,22,9,13,4,]

layer_repetition_no_BN_layer_sort_inverse_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [6,2,3,1,1,1,1,1,]
        - [9,3,4,2,2,1,2,1,]
        - [15,5,7,3,4,2,2,2,]
        - [21,7,10,4,5,3,3,3,]
        - [29,10,15,6,7,4,5,4,]
        - [59,20,29,12,15,8,10,7,]

layer_repetition_no_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,3,2,2,1,2,1,]
        - [5,4,5,2,4,1,2,1,]
        - [8,6,8,4,6,2,4,2,]
        - [11,8,11,6,8,3,6,3,]
        - [16,12,16,8,12,4,8,4,]
        - [32,24,32,16,24,8,16,8,]

layer_repetition_no_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,2,2,2,1,2,1,]
        - [4,4,4,3,3,2,3,1,]
        - [7,7,7,5,5,2,5,2,]
        - [10,10,10,7,6,3,7,3,]
        - [14,14,14,9,9,5,10,5,]
        - [28,28,28,19,19,10,19,9,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,2,4,1,2,1,1,1,]
        - [6,3,6,2,3,1,2,1,]
        - [10,5,10,3,5,2,3,2,]
        - [13,7,13,5,7,3,5,3,]
        - [19,10,19,6,10,5,6,5,]
        - [38,19,38,13,19,10,13,10,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 0.471
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,2,2,1,1,1,]
        - [5,5,5,2,2,2,2,1,]
        - [8,8,8,4,4,2,4,2,]
        - [11,11,11,5,5,4,5,4,]
        - [16,15,15,8,8,5,8,5,]
        - [31,31,31,16,15,10,16,10,]

