#### SEML and SLURM config

seml:
  executable: main.py
  name: SVHN_LeNet5_no_noise
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter


#### Experiment config

fixed:
  general:
    num_epochs: 200
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: SVHN
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 6
    step: 1
  model.LeNet.conf_name:
    type: choice
    options:
      - LeNet5
      - LeNet5-BN
      - LeNet5-BN-noNoise

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

no_noise_clamped:
  fixed:
    general.weight_clamping:
      min: -1
      max: 1
    noise_settings.default.noise_type: NoNoise
