#### SEML and SLURM config

seml:
  executable: main.py
  name: FashionMNIST_LeNet5_global_noise
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter


#### Experiment config

fixed:
  general:
    num_epochs: 200
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: FashionMNIST
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 5
    step: 1
  model.LeNet.conf_name:
    type: choice
    options:
      - LeNet5
      - LeNet5-BN
      - LeNet5-BN-noNoise
  noise_settings.default.enable_in_training:
    type: choice
    options:
      - 1
      - 0

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

gauss_add_clamped:
  fixed:
    general.weight_clamping:
      min: -1
      max: 1
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17

gauss_add:
  fixed:
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17

gauss_mul:
  fixed:
    noise_settings.default:
      noise_type: GaussMul
      GaussMean: 1.0
  grid:
    noise_settings.default:
      GaussStd:
        type: uniform
        min: 0
        max: 2.
        num: 21
