#### SEML and SLURM config

seml:
  executable: main.py
  name: GSC2_mlp_no_noise
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # Dummy setting


#### Experiment config

fixed:
  general:
    num_epochs: 150
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 0.0005
  data:
    dataset: GSC2_TF
    batch_size: 512
  model:
    model_class: MLP
    criterion: CrossEntropyLoss
    weight_criterion: True
  noise_settings.layer_wise: None

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 10
    step: 1
  model.MLP.conf_name:
    type: choice
    options:
      - RL_TFC
      - RL_TFC-noBN
      - RL_TFC-BN-noNoise

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

no_noise_clamped:
  fixed:
    general.weight_clamping:
      min: -1
      max: 1
    noise_settings.default.noise_type: NoNoise
